#!/bin/bash
#iPhone SE
if [ -d "/System/Library/PrivateFrameworks/CMCapture.framework/N69" ] 
then
    echo "N69 exists - iPhone SE Detected." 

mkdir "/Library/Application Support/11Cam15/N69BAK/"
    
cp -R /System/Library/PrivateFrameworks/CMCapture.framework/N69/AVCaptureSession.plist "/Library/Application Support/11Cam15/N69BAK/"
rm -rf /System/Library/PrivateFrameworks/CMCapture.framework/N69/AVCaptureSession.plist

cp -R "/Library/Application Support/11Cam15/N69/AVCaptureSession.plist" /System/Library/PrivateFrameworks/CMCapture.framework/N69/

else
    echo "Error: N69 does not exists."
fi
if [ -d "/System/Library/PrivateFrameworks/CMCapture.framework/N69u" ] 
then
    echo "N69u exists - iPhone SE Detected." 

mkdir "/Library/Application Support/11Cam15/N69uBAK/"
    
cp -R /System/Library/PrivateFrameworks/CMCapture.framework/N69u/AVCaptureSession.plist "/Library/Application Support/11Cam15/N69uBAK/"
rm -rf /System/Library/PrivateFrameworks/CMCapture.framework/N69u/AVCaptureSession.plist

cp -R "/Library/Application Support/11Cam15/N69/AVCaptureSession.plist" /System/Library/PrivateFrameworks/CMCapture.framework/N69u/

else
    echo "Error: N69u does not exists."
fi
# iPhone 7
if [ -d "/System/Library/PrivateFrameworks/CMCapture.framework/D101" ] 
then
    echo "D101 exists - iPhone 7 Detected." 

mkdir "/Library/Application Support/11Cam15/D101BAK/"
    
cp -R /System/Library/PrivateFrameworks/CMCapture.framework/D101/AVCaptureSession.plist "/Library/Application Support/11Cam15/D101BAK/"
rm -rf /System/Library/PrivateFrameworks/CMCapture.framework/D101/AVCaptureSession.plist

cp -R "/Library/Application Support/11Cam15/D101/AVCaptureSession.plist" /System/Library/PrivateFrameworks/CMCapture.framework/D101/

else
    echo "Error: D101 does not exists."
fi
# iPhone 7+/8+
if [ -d "/System/Library/PrivateFrameworks/CMCapture.framework/D111" ] 
then
    echo "D111 exists - iPhone 7+ Detected." 

mkdir "/Library/Application Support/11Cam15/D111BAK/"
    
cp -R /System/Library/PrivateFrameworks/CMCapture.framework/D111/AVCaptureSession.plist "/Library/Application Support/11Cam15/D111BAK/"
rm -rf /System/Library/PrivateFrameworks/CMCapture.framework/D111/AVCaptureSession.plist

cp -R "/Library/Application Support/11Cam15/D111/AVCaptureSession.plist" /System/Library/PrivateFrameworks/CMCapture.framework/D111/

else
    echo "Error: D111 does not exists."
fi
if [ -d "/System/Library/PrivateFrameworks/CMCapture.framework/D211" ]
then
    echo "D211 exists - iPhone 8+ Detected." 

mkdir "/Library/Application Support/11Cam15/D211BAK/"
    
cp -R /System/Library/PrivateFrameworks/CMCapture.framework/D211/AVCaptureSession.plist "/Library/Application Support/11Cam15/D211BAK/"
rm -rf /System/Library/PrivateFrameworks/CMCapture.framework/D211/AVCaptureSession.plist

cp -R "/Library/Application Support/11Cam15/D211/AVCaptureSession.plist" /System/Library/PrivateFrameworks/CMCapture.framework/D211/

else
    echo "Error: D211 does not exists."
fi
