#!/bin/bash
# iPhone SE
if [ -d "/System/Library/PrivateFrameworks/CMCapture.framework/N69" ] 
then
    echo "N69 exists - iPhone SE Detected." 
    
    rm -rf /System/Library/PrivateFrameworks/CMCapture.framework/N69/AVCaptureSession.plist
    cp -R "/Library/Application Support/11Cam15/N69BAK/AVCaptureSession.plist" /System/Library/PrivateFrameworks/CMCapture.framework/N69/
    rm -rf "/Library/Application Support/11Cam15/N69BAK/AVCaptureSession.plist"

else
    echo "Error: N69 does not exists."
fi
if [ -d "/System/Library/PrivateFrameworks/CMCapture.framework/N69u" ] 
then
    echo "N69u exists - iPhone SE Detected." 
    
    rm -rf /System/Library/PrivateFrameworks/CMCapture.framework/N69u/AVCaptureSession.plist
    cp -R "/Library/Application Support/11Cam15/N69uBAK/AVCaptureSession.plist" /System/Library/PrivateFrameworks/CMCapture.framework/N69u/
    rm -rf "/Library/Application Support/11Cam15/N69uBAK/AVCaptureSession.plist"

else
    echo "Error: N69u does not exists."
fi

# iPhone 7
if [ -d "/System/Library/PrivateFrameworks/CMCapture.framework/D101" ] 
then
    echo "D101 exists - iPhone 7 Detected." 
    
    rm -rf /System/Library/PrivateFrameworks/CMCapture.framework/D101/AVCaptureSession.plist
    cp -R "/Library/Application Support/11Cam15/D101BAK/AVCaptureSession.plist" /System/Library/PrivateFrameworks/CMCapture.framework/D101/
    
else
    echo "Error: D101 does not exists."
fi

# iPhone 7+
if [ -d "/System/Library/PrivateFrameworks/CMCapture.framework/D111" ] 
then
    echo "D111 exists - iPhone 7+ Detected." 
    
    rm -rf /System/Library/PrivateFrameworks/CMCapture.framework/D111/AVCaptureSession.plist
    cp -R "/Library/Application Support/11Cam15/D111BAK/AVCaptureSession.plist" /System/Library/PrivateFrameworks/CMCapture.framework/D111/
    
else
    echo "Error: D111 does not exists."
fi
# iPhone 8+
if [ -d "/System/Library/PrivateFrameworks/CMCapture.framework/D211" ] 
then
    echo "D211 exists - iPhone 8+ Detected." 

    rm -rf /System/Library/PrivateFrameworks/CMCapture.framework/D211/AVCaptureSession.plist
    cp -R "/Library/Application Support/11Cam15/D211BAK/AVCaptureSession.plist" /System/Library/PrivateFrameworks/CMCapture.framework/D211/
else
    echo "Error: D211 does not exists."
fi
# iPhone X
if [ -d "/System/Library/PrivateFrameworks/CMCapture.framework/D221" ] 
then
    echo "D221 exists - iPhone X Detected." 

    rm -rf /System/Library/PrivateFrameworks/CMCapture.framework/D221/AVCaptureSession.plist
    cp -R "/Library/Application Support/11Cam15/D221BAK/AVCaptureSession.plist" /System/Library/PrivateFrameworks/CMCapture.framework/D221/
else
    echo "Error: D221 does not exists."
fi

rm -rf "/Library/Application Support/11Cam15/*"
