#!/bin/bash


#iPhone SE
if [ -d "/System/Library/PrivateFrameworks/CMCapture.framework/N69" ] 
then
    echo "N69 exists - iPhone SE Detected." 

mkdir "/Library/Application Support/11Cam15/N69BAK/"
    
cp -R /System/Library/PrivateFrameworks/CMCapture.framework/N69/AVCaptureSession.plist "/Library/Application Support/11Cam15/N69BAK/"
rm -rf /System/Library/PrivateFrameworks/CMCapture.framework/N69/AVCaptureSession.plist

cp -R "/Library/Application Support/11Cam15/N69/AVCaptureSession.plist" /System/Library/PrivateFrameworks/CMCapture.framework/N69/

else
    echo "N69u does not exists - Not an iPhone SE."
fi
if [ -d "/System/Library/PrivateFrameworks/CMCapture.framework/N69u" ] 
then
    echo "N69u exists - iPhone SE Detected." 

mkdir "/Library/Application Support/11Cam15/N69uBAK/"
    
cp -R /System/Library/PrivateFrameworks/CMCapture.framework/N69u/AVCaptureSession.plist "/Library/Application Support/11Cam15/N69uBAK/"
rm -rf /System/Library/PrivateFrameworks/CMCapture.framework/N69u/AVCaptureSession.plist

cp -R "/Library/Application Support/11Cam15/N69u/AVCaptureSession.plist" /System/Library/PrivateFrameworks/CMCapture.framework/N69u/

else
    echo "N69u does not exists - Not an iPhone SE."
fi


#iPhone 6S
if [ -d "/System/Library/PrivateFrameworks/CMCapture.framework/N71" ] 
then
    echo "N71 exists - iPhone 6S Detected." 

mkdir "/Library/Application Support/11Cam15/N71BAK/"
    
cp -R /System/Library/PrivateFrameworks/CMCapture.framework/N71/AVCaptureSession.plist "/Library/Application Support/11Cam15/N71BAK/"
rm -rf /System/Library/PrivateFrameworks/CMCapture.framework/N71/AVCaptureSession.plist

cp -R "/Library/Application Support/11Cam15/N71/AVCaptureSession.plist" /System/Library/PrivateFrameworks/CMCapture.framework/N71/

else
    echo "N71 does not exists - Not an iPhone 6S."
fi
if [ -d "/System/Library/PrivateFrameworks/CMCapture.framework/N71m" ] 
then
    echo "N71m exists - iPhone 6S Detected." 

mkdir "/Library/Application Support/11Cam15/N71mBAK/"
    
cp -R /System/Library/PrivateFrameworks/CMCapture.framework/N71m/AVCaptureSession.plist "/Library/Application Support/11Cam15/N71mBAK/"
rm -rf /System/Library/PrivateFrameworks/CMCapture.framework/N71m/AVCaptureSession.plist

cp -R "/Library/Application Support/11Cam15/N71m/AVCaptureSession.plist" /System/Library/PrivateFrameworks/CMCapture.framework/N71m/

else
    echo "N71m does not exists - Not an iPhone 6S."
fi


# iPhone 7
if [ -d "/System/Library/PrivateFrameworks/CMCapture.framework/D101" ] 
then
    echo "D101 exists - iPhone 7 Detected." 

mkdir "/Library/Application Support/11Cam15/D101BAK/"
    
cp -R /System/Library/PrivateFrameworks/CMCapture.framework/D101/AVCaptureSession.plist "/Library/Application Support/11Cam15/D101BAK/"
rm -rf /System/Library/PrivateFrameworks/CMCapture.framework/D101/AVCaptureSession.plist

cp -R "/Library/Application Support/11Cam15/D101/AVCaptureSession.plist" /System/Library/PrivateFrameworks/CMCapture.framework/D101/

else
    echo "D101 does not exists - Not an iPhone 7."
fi


# iPhone 7+
if [ -d "/System/Library/PrivateFrameworks/CMCapture.framework/D111" ] 
then
    echo "D111 exists - iPhone 7+ Detected." 

mkdir "/Library/Application Support/11Cam15/D111BAK/"
    
cp -R /System/Library/PrivateFrameworks/CMCapture.framework/D111/AVCaptureSession.plist "/Library/Application Support/11Cam15/D111BAK/"
rm -rf /System/Library/PrivateFrameworks/CMCapture.framework/D111/AVCaptureSession.plist

cp -R "/Library/Application Support/11Cam15/D111/AVCaptureSession.plist" /System/Library/PrivateFrameworks/CMCapture.framework/D111/

else
    echo "D111 does not exists - Not an iPhone 7+."
fi


# iPhone 8+
# if [ -d "/System/Library/PrivateFrameworks/CMCapture.framework/D211" ]
# then
#    echo "D211 exists - iPhone 8+ Detected." 

# mkdir "/Library/Application Support/11Cam15/D211BAK/"
    
# cp -R /System/Library/PrivateFrameworks/CMCapture.framework/D211/AVCaptureSession.plist "/Library/Application Support/11Cam15/D211BAK/"
# rm -rf /System/Library/PrivateFrameworks/CMCapture.framework/D211/AVCaptureSession.plist

# cp -R "/Library/Application Support/11Cam15/D211/AVCaptureSession.plist" /System/Library/PrivateFrameworks/CMCapture.framework/D211/

# else
#    echo "D211 does not exists - Not an iPhone 8+."
# fi


#iPhone X
if [ -d "/System/Library/PrivateFrameworks/CMCapture.framework/D221" ] 
then
    echo "D221 exists - iPhone X Detected." 

mkdir "/Library/Application Support/11Cam15/D221BAK/"
    
cp -R /System/Library/PrivateFrameworks/CMCapture.framework/D221/AVCaptureSession.plist "/Library/Application Support/11Cam15/D221BAK/"
rm -rf /System/Library/PrivateFrameworks/CMCapture.framework/D221/AVCaptureSession.plist

cp -R "/Library/Application Support/11Cam15/D221/AVCaptureSession.plist" /System/Library/PrivateFrameworks/CMCapture.framework/D221/

else
    echo "D221 does not exists - Not an iPhone X."
fi

    echo "REBOOT REBOOT REBOOT"
