#!/bin/bash

# iPhone SE
if [ -d "/System/Library/PrivateFrameworks/CMCapture.framework/N69" ] 
then
    echo "N69 exists - iPhone SE Detected." 
    
    rm -rf /System/Library/PrivateFrameworks/CMCapture.framework/N69/AVCaptureSession.plist
    cp -R "/Library/Application Support/11Cam15/N69BAK/AVCaptureSession.plist" /System/Library/PrivateFrameworks/CMCapture.framework/N69/
    rm -rf "/Library/Application Support/11Cam15/N69BAK/AVCaptureSession.plist"
    rm -rf "/Library/Application Support/11Cam15/N69BAK/"

mv /Library/MobileSubstrate/DynamicLibraries/11Cam15Dual.dylibbak /Library/MobileSubstrate/DynamicLibraries/11Cam15Dual.dylib
mv /Library/MobileSubstrate/DynamicLibraries/11Cam15Dual.plistbak /Library/MobileSubstrate/DynamicLibraries/11Cam15Dual.plist

else
    echo "Error: N69 does not exists."
fi
if [ -d "/System/Library/PrivateFrameworks/CMCapture.framework/N69u" ] 
then
    echo "N69u exists - iPhone SE Detected." 
    
    rm -rf /System/Library/PrivateFrameworks/CMCapture.framework/N69u/AVCaptureSession.plist
    cp -R "/Library/Application Support/11Cam15/N69uBAK/AVCaptureSession.plist" /System/Library/PrivateFrameworks/CMCapture.framework/N69u/
    rm -rf "/Library/Application Support/11Cam15/N69uBAK/AVCaptureSession.plist"
    rm -rf "/Library/Application Support/11Cam15/N69uBAK/"

else
    echo "Error: N69u does not exists."
fi
# iPhone 6S
if [ -d "/System/Library/PrivateFrameworks/CMCapture.framework/N71" ] 
then
    echo "N71 exists - iPhone 6S Detected." 
    
    rm -rf /System/Library/PrivateFrameworks/CMCapture.framework/N71/AVCaptureSession.plist
    cp -R "/Library/Application Support/11Cam15/N71BAK/AVCaptureSession.plist" /System/Library/PrivateFrameworks/CMCapture.framework/N71/
    rm -rf "/Library/Application Support/11Cam15/N71BAK/AVCaptureSession.plist"
    rm -rf "/Library/Application Support/11Cam15/N71BAK/"

mv /Library/MobileSubstrate/DynamicLibraries/11Cam15Dual.dylibbak /Library/MobileSubstrate/DynamicLibraries/11Cam15Dual.dylib
mv /Library/MobileSubstrate/DynamicLibraries/11Cam15Dual.plistbak /Library/MobileSubstrate/DynamicLibraries/11Cam15Dual.plist

else
    echo "Error: N71 does not exists."
fi
if [ -d "/System/Library/PrivateFrameworks/CMCapture.framework/N71m" ] 
then
    echo "N71m exists - iPhone 6S Detected." 
    
    rm -rf /System/Library/PrivateFrameworks/CMCapture.framework/N71m/AVCaptureSession.plist
    cp -R "/Library/Application Support/11Cam15/N71mBAK/AVCaptureSession.plist" /System/Library/PrivateFrameworks/CMCapture.framework/N71m/
    rm -rf "/Library/Application Support/11Cam15/N71mBAK/AVCaptureSession.plist"
    rm -rf "/Library/Application Support/11Cam15/N71mBAK/"

else
    echo "Error: N71m does not exists."
fi
# iPhone 7
if [ -d "/System/Library/PrivateFrameworks/CMCapture.framework/D10" ] 
then
    echo "D10 exists - iPhone 7 Detected." 
    
    rm -rf /System/Library/PrivateFrameworks/CMCapture.framework/D10/AVCaptureSession.plist
    cp -R "/Library/Application Support/11Cam15/D10BAK/AVCaptureSession.plist" /System/Library/PrivateFrameworks/CMCapture.framework/D10/
    rm -rf "/Library/Application Support/11Cam15/D10BAK/AVCaptureSession.plist"
    rm -rf "/Library/Application Support/11Cam15/D10BAK/"

mv /Library/MobileSubstrate/DynamicLibraries/11Cam15Dual.dylibbak /Library/MobileSubstrate/DynamicLibraries/11Cam15Dual.dylib
mv /Library/MobileSubstrate/DynamicLibraries/11Cam15Dual.plistbak /Library/MobileSubstrate/DynamicLibraries/11Cam15Dual.plist

else
    echo "Error: D10 does not exists."
fi
if [ -d "/System/Library/PrivateFrameworks/CMCapture.framework/D101" ] 
then
    echo "D101 exists - iPhone 7 Detected." 
    
    rm -rf /System/Library/PrivateFrameworks/CMCapture.framework/D101/AVCaptureSession.plist
    cp -R "/Library/Application Support/11Cam15/D101BAK/AVCaptureSession.plist" /System/Library/PrivateFrameworks/CMCapture.framework/D101/
    rm -rf "/Library/Application Support/11Cam15/D101BAK/AVCaptureSession.plist"
    rm -rf "/Library/Application Support/11Cam15/D101BAK/"
else
    echo "Error: D101 does not exists."
fi

# iPhone 7+
if [ -d "/System/Library/PrivateFrameworks/CMCapture.framework/D111" ] 
then
    echo "D111 exists - iPhone 7+ Detected." 
    
    rm -rf /System/Library/PrivateFrameworks/CMCapture.framework/D111/AVCaptureSession.plist
    cp -R "/Library/Application Support/11Cam15/D111BAK/AVCaptureSession.plist" /System/Library/PrivateFrameworks/CMCapture.framework/D111/
    rm -rf "/Library/Application Support/11Cam15/D111BAK/AVCaptureSession.plist"
    rm -rf "/Library/Application Support/11Cam15/D111BAK/"
    
mv /Library/MobileSubstrate/DynamicLibraries/11Cam15Single.dylibbak /Library/MobileSubstrate/DynamicLibraries/11Cam15Single.dylib
mv /Library/MobileSubstrate/DynamicLibraries/11Cam15Single.plistbak /Library/MobileSubstrate/DynamicLibraries/11Cam15Single.plist

else
    echo "Error: D111 does not exists."
fi
# iPhone 8+
if [ -d "/System/Library/PrivateFrameworks/CMCapture.framework/D211" ] 
then
   echo "D211 exists - iPhone 8+ Detected." 

   rm -rf /System/Library/PrivateFrameworks/CMCapture.framework/D211/AVCaptureSession.plist
   cp -R "/Library/Application Support/11Cam15/D211BAK/AVCaptureSession.plist" /System/Library/PrivateFrameworks/CMCapture.framework/D211/
   rm -rf "/Library/Application Support/11Cam15/D211BAK/AVCaptureSession.plist"
   rm -rf "/Library/Application Support/11Cam15/D211BAK/"

mv /Library/MobileSubstrate/DynamicLibraries/11Cam15Single.dylibbak /Library/MobileSubstrate/DynamicLibraries/11Cam15Single.dylib
mv /Library/MobileSubstrate/DynamicLibraries/11Cam15Single.plistbak /Library/MobileSubstrate/DynamicLibraries/11Cam15Single.plist

else
   echo "Error: D211 does not exists."
fi
# iPhone X
if [ -d "/System/Library/PrivateFrameworks/CMCapture.framework/D221" ] 
then
    echo "D221 exists - iPhone X Detected." 

    rm -rf /System/Library/PrivateFrameworks/CMCapture.framework/D221/AVCaptureSession.plist
    cp -R "/Library/Application Support/11Cam15/D221BAK/AVCaptureSession.plist" /System/Library/PrivateFrameworks/CMCapture.framework/D221/
    rm -rf "/Library/Application Support/11Cam15/D221BAK/AVCaptureSession.plist"
    rm -rf "/Library/Application Support/11Cam15/D221BAK/"

mv /Library/MobileSubstrate/DynamicLibraries/11Cam15Single.dylibbak /Library/MobileSubstrate/DynamicLibraries/11Cam15Single.dylib
mv /Library/MobileSubstrate/DynamicLibraries/11Cam15Single.plistbak /Library/MobileSubstrate/DynamicLibraries/11Cam15Single.plist

else
    echo "Error: D221 does not exists."
fi

rm -rf "/Library/Application Support/11Cam15/*"

echo "Flushing camera formats..."
rm -f /var/mobile/Library/Preferences/com.apple.cameracapture.volatile.plist

echo "Killing mediaserverd..."
killall mediaserverd || true
