FINALPACKAGE=1
ARCHS = arm64
TARGET = iphone:14.5
INSTALL_TARGET_PROCESSES = Camera

include $(THEOS)/makefiles/common.mk

TWEAK_NAME = 11Cam15Single
11Cam15Single_FILES = Tweak.x
11Cam15Single_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/tweak.mk
